# Entendendo Numpy e Array

- Numpy é uma biblioteca de algébra linear voltado para criação existentes para análise de dados. 

- Array é apenas uma estrutura de dados independente em que será armazenado.

In [3]:
import numpy as np 

In [4]:
#Array a partir de uma lista
quantidade = [2,5,10,20,35]
custo = [100,150,450,320,195]

In [10]:
array1 = np.array(quantidade)
array2 = np.array(custo)

In [11]:
estoque = array1*array2

In [ ]:
estoque

In [13]:
custo2 =[100,200,300,400]
venda = [125,235,355,490]

In [15]:
array3 = np.array(custo2)
array4 = np.array(venda)

In [16]:
lucro = array4 - array3

In [17]:
lucro

array([25, 35, 55, 90])

In [18]:
#Arrays a partir do Numpy
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
np.arange(10,21,2,dtype=float)

array([10., 12., 14., 16., 18., 20.])

In [21]:
#Linspace
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
#Random - rand,randn e randint
rand = np.random.rand(10)
randn = np.random.randn(15)
randint = np.random.randint(10,100,30)

In [29]:
rand

array([22, 19, 17, 44, 33, 45, 68, 88, 43, 39, 61, 41, 14, 67, 55, 68, 30,
       42, 24, 72, 18, 16, 80, 48, 68, 77, 24, 88, 20, 66])

In [30]:
randn

array([ 0.84140423, -1.40703922,  0.36378616,  0.29117833,  0.9699599 ,
       -0.62789573,  1.38309992,  0.59025298, -0.33743033, -0.31613906,
        0.57652206, -0.66029401, -0.07669333,  0.15400465,  0.53968472])

In [31]:
randint

array([22, 19, 17, 44, 33, 45, 68, 88, 43, 39, 61, 41, 14, 67, 55, 68, 30,
       42, 24, 72, 18, 16, 80, 48, 68, 77, 24, 88, 20, 66])

In [32]:
len(randint)

30

In [33]:
#Zeros e uns
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Indexação de Arrays

In [4]:
#Unidimensional
numbers = np.arange(1,11,dtype=int)

In [6]:
#Indexação de arrays unidimensionais
numbers[4]

5

In [7]:
numbers[4:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
 #Bidimensional 
 numbersBid = np.random.randint(10,50,size=(3,3))

In [10]:
numbersBid

array([[32, 13, 16],
       [13, 37, 47],
       [15, 30, 22]])

In [11]:
numbersBid[0][0]

32

In [12]:
numbersBid[2][0:2]

array([15, 30])

In [13]:
arr = np.random.randint(1,101,size=(10,10))

In [14]:
arr

array([[ 30,  49,  16,  88,  59,  28,  77,   7,  70,  31],
       [ 27,  16,  38,  93,  61,  48,  73,  44,  35,  38],
       [ 75,  36,  19,  43,  28,  36,  54,  69,  29,  89],
       [ 15,  12,  60,  25,   7,  26,   8,  39,  63,  19],
       [ 96,  92,  92,  20,  95,  38,  99,  55,  81,  86],
       [ 48,  91,  57,  68,  11,  98,  42,  97,  85,  32],
       [ 26,  36,  46,  89,  79,  36,  75,  50,  59,  85],
       [ 97,  51,  99,  33,  18,  69,  90,  83,  94,  86],
       [ 51,  75,  69,  94,  29,   9,  77,  94, 100,  57],
       [ 97,  48,  92,  81,   3,  89,  77,  27,   1,  12]])

In [15]:
arr[:,7:]

array([[  7,  70,  31],
       [ 44,  35,  38],
       [ 69,  29,  89],
       [ 39,  63,  19],
       [ 55,  81,  86],
       [ 97,  85,  32],
       [ 50,  59,  85],
       [ 83,  94,  86],
       [ 94, 100,  57],
       [ 27,   1,  12]])

In [16]:
arr[:,6:9]

array([[ 77,   7,  70],
       [ 73,  44,  35],
       [ 54,  69,  29],
       [  8,  39,  63],
       [ 99,  55,  81],
       [ 42,  97,  85],
       [ 75,  50,  59],
       [ 90,  83,  94],
       [ 77,  94, 100],
       [ 77,  27,   1]])